prunus:
  fileupload:
    rootLocation: /Users/yongsang/prunus/upload # 본인 환경에 맞는 경로로 변경하세요.
spring:
  servlet:
    multipart:
      file-size-threshold: 0B
      max-file-size: 10MB
      max-request-size: 100MB
      location: /Users/yongsang/temp
  datasource:
    url: jdbc:h2:mem:upload
    username: sa
