CREATE TABLE PRUNUS_FILE_BUCKET (
    FILE_BUCKET_ID VARCHAR2(36),
    BACK_NUMBER VARCHAR2(8),
    ORIGINAL_FILENAME VARCHAR2(100) NOT NULL,
    CHANGED_FILENAME VARCHAR2(36) NOT NULL,
    EXTENSION VARCHAR2(20),
    SIZE BIGINT NOT NULL,
    LOCATION VARCHAR2(200) NOT NULL,
    DELETED BOOLEAN NOT NULL,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATETIME,
    CREATED_REMOTE_ADDR VARCHAR2(30),
    MODIFIED_BY VARCHAR2(30),
    MODIFIED_DATE DATETIME,
    MODIFIED_REMOTE_ADDR VARCHAR2(30),

    PRIMARY KEY (FILE_BUCKET_ID, BACK_NUMBER)
);
