spring:
  messages:
    basename: messages/message, messages/valid
    encoding: UTF-8

server:
  error:
    include-message: always  # 에러메세지 출력
    include-binding-errors: always  # binding 에러메세지 출력

