spring:
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    properties.hibernate:
      diarect: org.hibernate.dialect.H2Dialect # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
      show_sql: true # sql 쿼리를 보여줍니다.
      format_sql: true # sql query formatting
      use_sql_comments: true # sql 쿼리의 추가정보를 보여줍니다.
  data.web.pageable:
    default-page-size: 10
    one-indexed-parameters: true # page number 를 '1'부터 시작한다. (default : false, start at 0)
  h2.console:
    enabled: true
    settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:prunus
    username: sa
    password:
prunus:
  persistence:
    data.audit.modify-on-create: true
    mybatis:
      audit.enabled: true
      pagination.enabled: true
