INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, SALARY, HIRE_DATE, MARRIED, EMAIL, FILE_BUCKET_ID, BACK_NUMBER, DEPARTMENT_ID, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('it0324', '홍길동', 2000, '2008-10-15', 1, 'it0324@korea.com', NULL, NULL, '120301', 'admin', NOW(), 'admin', NOW());

INSERT INTO EDUCATION (EMPLOYEE_ID, SCHOOL_NAME, GRADUATION_YEAR, GRADUATION_TYPE, GRADES, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('it0324', '서울초등학교', '199002', '10', NULL, 'admin', NOW(), 'admin', NOW());
INSERT INTO EDUCATION (EMPLOYEE_ID, SCHOOL_NAME, GRADUATION_YEAR, GRADUATION_TYPE, GRADES, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('it0324', '서울중학교', '199302', '10', NULL, 'admin', NOW(), 'admin', NOW());
INSERT INTO EDUCATION (EMPLOYEE_ID, SCHOOL_NAME, GRADUATION_YEAR, GRADUATION_TYPE, GRADES, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('it0324', '서울고등학교', '199602', '10', NULL, 'admin', NOW(), 'admin', NOW());
INSERT INTO EDUCATION (EMPLOYEE_ID, SCHOOL_NAME, GRADUATION_YEAR, GRADUATION_TYPE, GRADES, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('it0324', '서울대학교', '200202', '10', 4.0, 'admin', NOW(), 'admin', NOW());

INSERT INTO DEPARTMENT (ID, NAME, LOCATION, CRE_USER, CRE_DATE, MOD_USER, MOD_DATE) VALUES ('120301', 'QA팀', '안국동', 'admin', NOW(), 'admin', NOW());