/**
  사원 테이블
 */
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID VARCHAR2(20),
    EMPLOYEE_NAME VARCHAR2(20),
    SALARY INT,
    HIRE_DATE DATETIME,
    MARRIED INT,
    EMAIL VARCHAR2(50),
    FILE_BUCKET_ID VARCHAR2(36),
    BACK_NUMBER VARCHAR2(8),
    DEPARTMENT_ID VARCHAR2(20),
    CRE_USER VARCHAR2(20),
    CRE_DATE DATETIME,
    MOD_USER VARCHAR2(20),
    MOD_DATE DATETIME,
    PRIMARY KEY (ID)
);

/**
  사원 학력 테이블
 */
CREATE TABLE IF NOT EXISTS EDUCATION (
    ID INT AUTO_INCREMENT,
    EMPLOYEE_ID VARCHAR(20),
    SCHOOL_NAME VARCHAR(30),
    GRADUATION_YEAR VARCHAR(6),
    GRADUATION_TYPE VARCHAR(50),
    GRADES NUMBER,
    CRE_USER VARCHAR2(20),
    CRE_DATE DATETIME,
    MOD_USER VARCHAR2(20),
    MOD_DATE DATETIME,
    PRIMARY KEY (ID)
);

/**
  부서 테이블
 */
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    ID VARCHAR(20),
    NAME VARCHAR(20),
    LOCATION VARCHAR(50),
    CRE_USER VARCHAR2(20),
    CRE_DATE DATETIME,
    MOD_USER VARCHAR2(20),
    MOD_DATE DATETIME,
    PRIMARY KEY (ID)
);