spring:
  data:
    web:
      pageable:
        default-page-size: 10
prunus:
  nexacro:
    adaptor:
      argument-resolver:
        enabled: true
      message-converter:
        enabled: true
      data-set:
        column-case: lower-camel # lower-camel, lower-underscore, lower-hyphen, upper-camel, upper-underscore
