DROP SEQUENCE IF EXISTS LAPTOP_ID_SEQUENCE;

CREATE SEQUENCE LAPTOP_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS LAPTOP;

CREATE TABLE LAPTOP (
    ID BIGINT,
    VENDOR VARCHAR2(100) NOT NULL,
    DISPLAY_SIZE BIGINT NOT NULL,
    DELETED BOOLEAN NOT NULL,
    CRE_USER VARCHAR2(30),
    CRE_DATE DATETIME,
    CRE_ADDR VARCHAR2(30),
    CRE_DEPT VARCHAR2(30),
    MOD_USER VARCHAR2(30),
    MOD_DATE DATETIME,
    MOD_ADDR VARCHAR2(30),
    MOD_DEPT VARCHAR2(30),
    PRIMARY KEY (ID)
);